version: '3.8'

networks:
  main:

volumes:
  vue_build:

services:
  django:
    build: ./backend/github_clone/
    command: gunicorn github_clone.wsgi --bind 0.0.0.0:8000
    networks:
      main:
        aliases:
            - django
    volumes:
      - ./github_clone/:/usr/src/app/
    ports:
      - "8000:8000"
    expose:
      - 3000
    env_file:
      - ./backend/.env
    depends_on:
      - gitea

  vue:
    build: ./front/github_clone_front
    command: tail -f /dev/null
    networks:
        main:
          aliases:
            - vue
    volumes:
      - vue_build:/vue/build
  

  nginx:
    build:
      context: ./nginx/
    networks:
        main:
          aliases:
            - nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - vue_build:/var/www/vue
    depends_on:
      - django
      - vue
      
  gitea:
    image: gitea/gitea:1.21.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      main:
        aliases:
          - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
    ports:
      - "3000:3000"
      - "222:22"