version: '3.8'

networks:
  main:

services:
  web:
    build: ./github_clone/
    command: gunicorn github_clone.wsgi:application --bind 0.0.0.0:8000
    networks:
      main:
        aliases:
            - web
    volumes:
      - ./github_clone/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - gitea

  nginx:
    build:
      context: ./nginx/
    networks:
        main:
          aliases:
            - nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web
      
  gitea:
    image: gitea/gitea:1.21.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      main:
        aliases:
          - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
    ports:
      - "3000:3000"
      - "222:22"