# Generated by Django 4.2.7 on 2024-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='main.label'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='milestones', to='main.label'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='pull_requests', to='main.label'),
        ),
    ]
