# Generated by Django 4.2.7 on 2024-05-16 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(default='', max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='main.project'),
        ),
        migrations.AddField(
            model_name='watches',
            name='issue_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watches',
            name='option',
            field=models.CharField(choices=[('Participating', 'Participating'), ('All', 'All'), ('Ignore', 'Ignore')], default='Participating', max_length=15),
        ),
        migrations.AddField(
            model_name='watches',
            name='pull_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watches',
            name='release_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 17, 15, 38, 18746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_release', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_commit', to='main.commit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_release', to='main.project')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_branch', to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request', to='main.pullrequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='main.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', to='main.label'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='milestones', to='main.label'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='pull_requests', to='main.label'),
        ),
    ]
