# Generated by Django 4.2.7 on 2023-11-27 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='contentchanged',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='event',
        ),
        migrations.AddField(
            model_name='assignment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contentchanged',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
