# Generated by Django 4.2.7 on 2024-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryemail',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondaryemail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
