# Generated by Django 4.2.7 on 2024-05-15 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 19, 13, 13, 132459, tzinfo=datetime.timezone.utc)),
        ),
    ]
