# Generated by Django 4.2.7 on 2024-04-22 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 11, 44, 19, 595553, tzinfo=datetime.timezone.utc)),
        ),
    ]
