# Generated by Django 4.2.7 on 2024-03-17 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 9, 56, 23, 280274, tzinfo=datetime.timezone.utc)),
        ),
    ]
