# Generated by Django 4.2.7 on 2024-04-20 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Unregistered', 'Unregistered'), ('Readonly', 'Readonly'), ('Developer', 'Developer'), ('Maintainer', 'Maintainer'), ('Owner', 'Owner'), ('IsBanned', 'IsBanned')], default='Developer', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 6, 16, 44, 49548, tzinfo=datetime.timezone.utc)),
        ),
    ]
