# Generated by Django 4.2.7 on 2024-04-13 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_timestamp_alter_issue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_issue', to='main.developer'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 26, 25, 426653, tzinfo=datetime.timezone.utc)),
        ),
    ]
