# Generated by Django 4.2.7 on 2024-04-22 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_issue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 11, 44, 56, 325554, tzinfo=datetime.timezone.utc)),
        ),
    ]
