# Generated by Django 4.2.7 on 2024-04-20 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invitation_role_alter_issue_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 21, 24, 47, 618400, tzinfo=datetime.timezone.utc)),
        ),
    ]
