# Generated by Django 4.2.7 on 2024-05-03 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_issue_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 14, 12, 37, 578480, tzinfo=datetime.timezone.utc)),
        ),
    ]
