# Generated by Django 4.2.7 on 2024-05-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_issue_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('General comment', 'General comment'), ('Approved', 'Approved'), ('Request changes', 'Request changes')], default='General comment', max_length=20)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_for_review', to='main.pullrequest')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_for_pr', to='main.developer')),
            ],
        ),
    ]
