# Generated by Django 4.2.7 on 2024-04-14 10:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_issue_created_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 10, 16, 30, 664962, tzinfo=datetime.timezone.utc)),
        ),
    ]
