# Generated by Django 4.2.7 on 2024-05-03 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_issue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='issue_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watches',
            name='option',
            field=models.CharField(choices=[('Participating', 'Participating'), ('All', 'All'), ('Ignore', 'Ignore')], default='Participating', max_length=15),
        ),
        migrations.AddField(
            model_name='watches',
            name='pull_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watches',
            name='release_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 47, 10, 561588, tzinfo=datetime.timezone.utc)),
        ),
    ]
