# Generated by Django 4.2.7 on 2024-04-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issue_creator_alter_issue_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 36, 23, 597887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='manager',
        ),
        migrations.AddField(
            model_name='issue',
            name='manager',
            field=models.ManyToManyField(blank=True, related_name='managed_issues', to='main.developer'),
        ),
    ]
