# Generated by Django 4.2.7 on 2024-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pullrequest_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
