# Generated by Django 4.2.7 on 2024-05-27 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pullrequestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestreview',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
