# Generated by Django 4.2.7 on 2024-05-15 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_issue_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 19, 15, 34, 839242, tzinfo=datetime.timezone.utc)),
        ),
    ]
