# Generated by Django 4.2.7 on 2023-12-04 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registrationcandidate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcandidate',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
