# Generated by Django 4.2.7 on 2024-04-20 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_issue_created_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fork',
            name='project',
        ),
        migrations.AddField(
            model_name='fork',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='main.project'),
        ),
        migrations.AddField(
            model_name='fork',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 21, 47, 46, 730699, tzinfo=datetime.timezone.utc)),
        ),
    ]
