# Generated by Django 4.2.7 on 2024-02-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pullrequest_description_pullrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_request_milestone', to='main.milestone'),
        ),
    ]
