# Generated by Django 4.2.7 on 2024-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='type',
            field=models.CharField(choices=[('issue', 'issue'), ('pull_request', 'pull_request'), ('milestone', 'milestone'), ('comment', 'comment')], default='pull_request', max_length=20),
        ),
    ]
