# Generated by Django 4.2.7 on 2024-02-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pullrequest_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_requests_assignee', to='main.developer'),
        ),
    ]
