# Generated by Django 4.2.7 on 2024-01-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workson',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Unregistered', 'Unregistered'), ('Reporter', 'Reporter'), ('Developer', 'Developer'), ('Maintainer', 'Maintainer'), ('Owner', 'Owner'), ('IsBanned', 'IsBanned')], default='Developer', max_length=20),
        ),
    ]
