# Generated by Django 4.2.7 on 2024-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pullrequest_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='gitea_id',
            field=models.IntegerField(null=True),
        ),
    ]
