# Generated by Django 4.2.7 on 2024-05-04 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification_is_read_notification_sent_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 17, 41, 49, 510841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PullRequestAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='main.developer')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request', to='main.pullrequest')),
            ],
        ),
    ]
