# Generated by Django 4.2.7 on 2024-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pullrequest_gitea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='mergable',
            field=models.BooleanField(null=True),
        ),
    ]
