# Generated by Django 4.2.7 on 2024-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_workson_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='gitea_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
