# Generated by Django 4.2.7 on 2024-01-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_developer_gitea_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
