# Generated by Django 4.2.7 on 2024-05-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_issue_created_alter_project_name'),
        ('main', '0008_pullrequestreviewer_alter_issue_created_and_more'),
    ]

    operations = [
    ]
