# Generated by Django 4.2.7 on 2024-02-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pullrequest_mergable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_requests_assignee', to='main.developer'),
        ),
    ]
