# Generated by Django 4.2.7 on 2024-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_developer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
