# Generated by Django 4.2.7 on 2024-05-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20240509_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 15, 38, 42, 507122, tzinfo=datetime.timezone.utc)),
        ),
    ]
