# Generated by Django 4.2.7 on 2024-02-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_pullrequest_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='mergable',
            new_name='mergeable',
        ),
    ]
