# Generated by Django 4.2.7 on 2024-05-11 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_issue_created_alter_tag_name_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='main.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 53, 53, 978736, tzinfo=datetime.timezone.utc)),
        ),
    ]
