# Generated by Django 4.2.7 on 2024-05-14 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_issue_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 19, 21, 42, 427004, tzinfo=datetime.timezone.utc)),
        ),
    ]
