# Generated by Django 4.2.7 on 2024-02-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_mergable_pullrequest_mergeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_requests_merged_by', to='main.developer'),
        ),
    ]
