# Generated by Django 4.2.7 on 2024-05-11 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tag_project_alter_issue_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='commitish',
        ),
        migrations.AddField(
            model_name='release',
            name='commit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='release_commit', to='main.commit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 15, 25, 1, 596092, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='release',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='main.project'),
        ),
    ]
