# Generated by Django 4.2.7 on 2024-01-30 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_branch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 22, 23, 30, 839721, tzinfo=datetime.timezone.utc)),
        ),
    ]
