# Generated by Django 4.2.7 on 2024-01-30 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_commit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
