# Generated by Django 4.2.7 on 2024-01-30 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pullrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
