# Generated by Django 4.2.7 on 2024-01-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_commit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='commits', to='main.tag'),
        ),
    ]
