# Generated by Django 4.2.7 on 2024-01-31 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_commit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='main.branch'),
        ),
    ]
