# Generated by Django 4.2.7 on 2024-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_branch_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
