# Generated by Django 4.2.7 on 2024-02-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_milestone_description_milestone_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='id_from_gitea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
