# Generated by Django 4.2.7 on 2024-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_commit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
